services:
  backend:
    build:
      context: ./backend
    pull_policy: build
    environment:
      - WEBUI_URL=${BASE_URL}:${WWW_PORT}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ${PATH_DT}:/app/data
      - ${PATH_OT}:/app/output
      - ${PATH_BP}:/app/blueprints
    restart: always
  frontend:
    build:
      context: ./frontend
      args:
        - API_URL=${BASE_URL}:${API_PORT}
    pull_policy: build
    volumes:
      - node_modules:/app/node_modules
    ports:
      - "${WWW_PORT}:4173"
    depends_on:
      - backend
    restart: always
volumes:
  node_modules: